# Generated by Django 5.1.3 on 2024-12-16 12:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="заголовок")),
                (
                    "content",
                    tinymce.models.HTMLField(blank=True, verbose_name="содержимое"),
                ),
            ],
            options={
                "verbose_name": "страница с содержимым",
                "verbose_name_plural": "страницы с содержимым",
            },
        ),
    ]
