# Generated by Django 5.1.3 on 2024-12-16 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specialties", "0002_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="содержимое"),
        ),
    ]
